apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  labels:
    app: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - args:
         - sleep 6000
         #-  odoo --db_host=$DB_HOST --database=$DB --db_user=$DB_USER  --db_password=$DB_PASSWORD --db_port=$DB_PORT
        command:
           - /bin/sh
           - '-c'
           - --
        name: odoo
        image: library/odoo:latest
        ports:
        - containerPort: 8069
        env:
        - name: HOST
          value: localhost
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: admin
        - name: DB_PORT
          value: '5432'
        - name: DB
          value: odoo2
        - name: DB_HOST
          value: '10.102.95.28'
---
apiVersion: v1
kind: Service
metadata:    
  name: odoo-service
spec:
  type: LoadBalancer
  selector:
    app: odoo
  ports:
    - protocol: TCP
      port: 8069
